apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: tekton-demo
spec:
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: tekton-demo:latest
