apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: my-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-ctr
        image: registry.redhat.io/rhel8/nginx-120
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
      volumes:
      - name: nginx-cache
        emptyDir: {}
