apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: my-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: image-registry.openshift-image-registry.svc:5000/my-gitops/nginx:1.25
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
      volumes:
      - name: nginx-cache
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: my-gitops
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-route
  namespace: my-gitops
spec:
  to:
    kind: Service
    name: nginx-service
  port:
    targetPort: http
  tls:
    termination: edge
