apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: my-gitops
  labels:
    app: ngnix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-ctr
        image: nginx:latest
        securityContext:
          runAsUser: 0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
