apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: my-gitops
  labels:
    app: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-ctr
        image: redis:latest
        
